#!/bin/bash
t=0
number=$(ls -1q wallpapers | wc -l)
n=$(shuf -i 1-$number -n 1)
name=0
echo $n
find "$HOME/wallpapers" | while read -r file; do
  name="$file"
  let ++t
  if [[ $t -eq $n ]]; then
    killall swaybg
    swaybg --image "$name";
    break
  fi
done

