theme = "mytheme"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
b = ":bn"
B = "buffer_picker"
f = [':sh if [[ -z "${ZELLIJ}" ]]; then exit; else zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash $HOME/.config/helix/ranger-pick open; fi']

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false
