theme = "mytheme"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
b = ":bn"
B = "buffer_picker"
x = ":bc"

[editor.file-picker]
hidden = true
ignore = true
git-ignore = false
git-global = false
git-exclude = false
